language: python
dist: trusty
sudo: required

jdk:
  - oraclejdk8

python:
  - "3.4"

addons:
  apt:
    sources:
    - chef-current-precise
    packages:
    - chefdk

before_script: ./travis-ci/before-script
script: ./travis-ci/script

env:
  global:
    # travis encrypt SONATYPE_USERNAME=...
    - secure: "QLvr8a96TKm2dDnKRl+42UB5P9xsybNZWfGVgzPBawp0BMjH2SoA4LuYX8EA2iwuYW9DtmrUjMLBl5WSRBCxcosHnsPpqENX18TjED4SPZI2yVPD/cKzv78Z1BeUdKn0F6xdPZG+eW0VEbJaCYYwQ6LWuJ2e9YE6AwlzAmdNnhUciLEWSuLT1HrbJivXZVIemjp2pzTFlq70xwYd6Vgq8vEzrzImW/s8DNZg/JimXOKYil77W2oGbJNOPL2sLHi3mCZ8NjDWB/+KhBeHjuB0Z8KQu9t+z0FNPdPGNAyi1j3mhinr5brwqwyqmbSqhzgK4LtIDc6/wUBEP/CALClH31gHGRTJoGZg/reZjuMY387HFkH0BhiIISUaucnJMXv/HuLE7958ENc9Wg6R/CSPY/aMkg1I6k/tNLXGPPQDq0+ZYoKtm2LQRQFLMsOO2xeyrKoY5/YM+YO0ZFY6mefdL5Y3y7TilKYGPFrXeoH3yYH4yDvYetBDfeG7wx2pBNDW+EnZ++D/x1CpCkBEz3AN+owO6pbPAmIwB3/XL9xEWAgNO1K7/XvgHWY8lS1mAJ1MuBTjxcH3p+vci943ex0KLxYaTqpt6sT4Z42UzUtJ8YPXoMOzcn7o3A0XYPxhbaUn2n81Qc2hxVPv0b//ogGyhwHZKHrCgUx8fRG9p0gpzKI="
    # travis encrypt 'SONATYPE_PASSWORD="..."'
    - secure: "kFy0X5eSuvzajSZl6YJhmS25ihCiwki1aoTH66f93JIkA8TZLd8BWjNiyXJ7dx1VIkrogj/8kugGxxQxHjOpYKJCZ4A4eaIVKWyEQERDQSyTCKACxJLn0Cgur3rEa4h/i9TYcqslT6/8aHOSn3GqXemfan2g3S/8+a3Ac6r5wTrge+8qcb75//kjOZteFeIRjR/gJhpClAKVun58tkZcHtQRWTXBEoYX7GbHOKg7DIfwAkn6cY53dGzqDMJPWeTdbj8BUYjp7hClcAW4NnMr5iSxj+mwUnagi5nUZigru+fMWkvuepQ9DRla7jD6yDIC4aGuIZwx0BNk3yFVSkcDW0oQ+PPQ+X5MCfeUo5dHc7hDr9t30XiqTwbE9OkOv1zoQELMrEsbdGUQNo7mk4dnAgwkCr7pNAIX/tJ1Yn2pQAMnPRgeKDWFDGLmLB2BUiW1DbUZirE+RQWhx9+l9BdbG5QMEOIf0jUeNdlC2qopTxyaf0x4kVdj8JE5PPNw6OKcURQk4bJ0LZSSoa4sOsskGR1uHCqXL9NdXHTYbWdCTUisWyb1vYCIow5v8MuRXNwc1m5bqPNBiVw7BUM0AqBN3zxQpffDRGOhgRMgwJUlr6Yj5C+sDsbuQ8VxEYitBkhct03DHsqWoE2QHkQh2FP98F86MNo6ufFD0lhBEPhuFu4="
    # travis encrypt GPG_KEYNAME=...
    - secure: "aXjvvdGnUhJ5AU+tB3nb6rGLgXTJglhitP+kObPdVYR+Yrey09giIrL3Jkp1vU4prS+GiV6DQJDLvUzDzH2saAOv8XQ/fVly9C8M1x3WZ07/RD7rFL+JUCAk5it6jkrRJ3/tV2QrPh4E9fNceKYA7NYjAWDAQAu7C8bivNU8wHR+yiQIG8q5ngDXxoWBV8/CCK5FLMvgOEWVZFUir/Jy4Y/Ipo6U9CIAQFgIMmRsHtgqGXN+7N9K8hRy8fhV0E8iu8hzbkX5DQthg1NgDhDXUqHTQtefdqvdHtKf7Fx4UeuTMWTstbrjI7ei/4z0QZspvdNQNPCWa2uwz94cQ/GziItL4YbuZB2Tn62uWYKDoRhg3RBYzDHcnFXFgpwoUNYi1Cej2GP8Tsm8Q3V1HIjKkzn4GGmNTU2q6nuhkjq9wcvzWWsCKy334RLFA+ZLkmnv9LMeXK9yGdbO96Dfsl9qGQihNT5O5zxvuda1XUyo868gvVR1URIZgN3yoz45lO4eXMQ5sqJC40qrViPRAyFnIb4AM9WT3jBipLKofcPzUUIFKbxj52HIRJQ2Z2T12MyGUb0vxnm0gmUSOVdYvnO5HC+rNNYJFNLrMD+VCNgradlpi7fBSqFrZKfvkSWiv0wnmhO4zlcMbJe6HZGOy7RVK7xaoqLtT75Xt4PlOHwdPik="
    # travis encrypt 'GPG_PASSPHRASE="..."'
    - secure: "lcx6KdpObgeA/kbCWIT0ZcKomas1fBcEHhTmM67voutCtcrzxyFTGwB1pP5O06SOff8l42xUR/qZ9rJ8pVe6lKQLFNaAg7JgvILY3yBw7SNJXSix+sFT4yOXvZnlk8KH+bDn8w3/pR8NM3P4Z4q5GfKdZZcoZI+JCIBRKxBuDcTG11tY8YsFA9zCBxUkDeH8qOxG5HVzP1C9lvlKZbZXqugQGVmhvDQi79Y4qU7/KF6rUM+bM2VYs3LLGsJBXrakOMLJP95b+h1JWlGPeboYfqAkYpUqvkQeplrkz4jtvkqKAJpbXXlaFReH1qbB1Q1adgjbgNQYwIH+SK6Il7gA+qwPTABvg+IGqmhp+n1SYFmhgfeNvzO0PICME8YH3oEFCzwz9PGMQmym14Pd3kGX6rHBHKUnvjis9q4adl8GaaQ/tv45x+t/yyj72x77a/uHyfpn0hcW1MsR2wFVA5aG1QKifaHQoCqUuGPhAncCMDC6Vl5dEumYJqEbYbV81YwSsT5otVSg/DMSqBRYPu+nJuN1xGFY+jb9Kcw4FDORL/OFPk9gNCJVd5jS4okakhpdKwG6tv2u9pgCk/xg77kMqb5n3ToyxpFgu4/hlohtS+wvX+z6Woko/iA9VBlhwzMK1lh4bfiojIRfnCJLFBbFdKxnn6rgzKGS24tv9Nu3vNc="
  matrix:
    - FIJI_HADOOP_DISTRIBUTION=cdh
      FIJI_HADOOP_DISTRIBUTION_VERSION=5.3.5

deploy:
  - provider: script
    script: ./devtools/deploy-jars
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      # travis encrypt $API_KEY
      secure: "Sp4G3S6ASN8Ub/GVOp/0JHVBSVjROiKRNSsJy6h5DCpzq+5VTjt49+U2Z9xiyOGIQ4XzDY2YNLfGjLHHJdWkwxQbaQkKEJIuB7NEWfoY5Cqt6GSagW/iIkDllXienXn8JbhnP46LQoUcDJzsx56LNEA7pWZrVwVUiNpkahCth1M4wV7sbFSl9ljzPmNur//+YIrt520qMNedVgsiDc/j50Sfx4ScO0K9IauEY8fTeKtbgsRoJnlIeYRrwGQ7jUHPm1TCjzZvp2PXE4hcFLWf9FrWxcCSklV05oA8ZwSn+WHMxNhreajMn4g8Y3/tUFfatioTc4rMlUZR5ltuczTumgbm7YsX2kcfpud5oy8ruyQWibij/9bv/tquZ79aDloiLBTsq5slesfeErmr+TZzmDlyuGDiM3krR/7aq7bUVKry0H4aLk2vGB6yyL7YJkGlQBbJocu9catzgqN3l8hvoASkhUQcEe7sWJsRn3X3cm/YIRc2n8YlyqiqujeB/5dRC4sz5q9HJXnMeP2qrbgoGXOsHuFCztIud17U0t6uKluIdDlNXC1q02yY76YmHXl4dEHiviQFjEL+FR2Lb5Efa2zNQH1Ezh3MugW0XWWEs6rrHrtuhLUFtojb9Uw3dylTFfoosLN5nc4/asVh8bJ7XmPM9VEkMpvGtuq+TedBwKs="
    file_glob: true
    file:
      - fiji-express/fiji-express/target/fiji-express-lib-*-release.tar.gz
      - fiji-express/fiji-express-examples/target/fiji-express-examples-*-release.tar.gz
      - fiji-express/fiji-express-tools/target/fiji-express-tools-*-release.tar.gz
      - fiji-hive-adapter/fiji-hive-adapter/target/fiji-hive-lib-*-release.tar.gz
      - fiji-hive-adapter/fiji-hive-tools/target/fiji-hive-tools-*-release.tar.gz
      - fiji-mapreduce/fiji-mapreduce/target/fiji-mapreduce-*-release.tar.gz
      - fiji-modeling/fiji-modeling/target/fiji-modeling-*-release.tar.gz
      - fiji-modeling/fiji-modeling-examples/target/fiji-modeling-examples-*-release.tar.gz
      - fiji-rest/fiji-rest/target/fiji-rest-lib-*-release.tar.gz
      - fiji-schema/fiji-schema/target/fiji-schema-*-release.tar.gz
      - fiji-schema-shell/target/fiji-schema-shell-lib-*-release.tar.gz
    skip_cleanup: true
    on:
      tags: true
