language: python
dist: trusty
sudo: required

jdk:
  - oraclejdk8

python:
  - "3.4"

addons:
  apt:
    sources:
    - chef-current-precise
    packages:
    - chefdk

before_script: ./travis-ci/before-script
script: ./travis-ci/script

env:
  global:
    # travis encrypt SONATYPE_USERNAME=...
    - secure: "cVj0CfQ8kfM2nFQTPelpvLDKeZ1cU0VkljDK+V9GBHdKrFqKT9RkbNADqmJ1gljcnk535LMd8P8RxWDEUxUlnCNIzNiSg9m/EIM7mccCnLOIwt1ses9etfhnWc63FCGc0bPV9S+AcAQvbNcDIm1d71o79cZ4rRpFq1wBITiNBHiKPzxRw6nnTNzYXlMw2E0x/NRGytMKqB1UaToJRf144j2VC4tRBkHyqWF+2Dyttk3Jr4K/mJPvFgFTsiFvWV+edUzgaSi6C6l0aBv7RWmKiXtaj1lV1jnO6tSsBQgrfqWtulGizPwmvuCeTxIyn98szuALsIAri5Z7e4QsnDWnPg3mEVd2J7apzh7qj5h1DVU1vFB9eCIUuiFVRLCu/zo6Dr7GPFDuEFHiu49ctNB7vm0QhAS9YVmqiI35o51Laraj+vo+vePlQ9nsce6Xd3kSaQzJf6bEGGJ6XGXDn3q4lOG6TwFlbTYn2eh/eLa3eiMfNUGRKm9WaUKHJPZJXcGY16Fx5SihheFJy9Yf0Jq6GevEyeAW9nvrXgwLF4WB3+HMMpUXbquU1rX/nnFTiLY6jdcLKrpKUIHgro2O5oZl/tepoRxlVDUTS6SY9lSCx7f6Nlc1tTHmkTwxE2wJ6lUd24PqZw408qV9c6r3W9dVY4QQ6ervZiYbEGtRqUZXDAg="
    # travis encrypt 'SONATYPE_PASSWORD="..."'
    - secure: "U+H/kNoGjutcXASXNAx1V9u2J+CLIBpl6cQC2zsHEQIhvro+J45loEH4RObT0L62r4dw1LWvYnIzYvhIcIsB5rACR29UEyOMfuP1+jiVXxU9ma3czT7AkG6sYsl9yVNTm7g5Drr/a9sskU1nwh6w6u9CQdnMtYerwQQSZF7y7WJv6g2/XXysu49elH7GsuOlUr1BaBFaIwATQwUtgT2by0NczADeYWiOh9oiObmWyYuEiRnyn0jgSlMYHc0i5SnOepNmh5DkgPp4ef2ExnesN/X74cyo+xe4DnhpkNzbJdyH6iAyPysQK1UeAcRgu6+dUe5BD2+dPzRkWmnvufqzTyY+GKzGr8XKQ6JvzQlmJyOTIyLxR+G87SBiqzlJVvM7EnHaG/M/N6wJ8N1NwGLZ9/pZyCt2thBYOSw4VFfckvHJZ3SxPiuBH40R2RIV7Pp2kzeRTZfgGRpK5xK1L+HsPHVpZ64orBD8gHAtSFejW8GNBTEtgP8BBq9ebMG+yEfqRigUW5V221xb2fVuh14xGnIBzruTosRVvOz62KwPanNoeb+c7JKuZ9ol8I2zWTzD+MDwsDObpFYNlaf7G0Xo6Pr98eSbRh4Ekfua/k2fFm3COxyyRWRUbzZlqPvaWa1nqE7ufr+0xjACDeHxmiE2gsqjizRpU/eItEniOrTLmhY="
    # travis encrypt GPG_KEYNAME=...
    - secure: "FTb5AQCucHXR866mtqiNcHDwVelXqF0d0yIX46FeFhNZs7AaFqORUyzLoL5tgOEjRp0FPSBCTdDDQDNJvQnsjEZpGrMRxPNTedZ3POuY3ZGFCa6jL+WrLMEy4b318jQxjkGkwVMFaRmgHsL5NP91IiRbuXvbztiW+/7Pz1Q2Dc3cADaWmfQt5rZ1JjfHEpUW/NbbyDLZSiCwJ2V7Z6d73h1d6cv8uhNr2gtazqJPgUp/R9iNQ8bGsFHlVPZh4IeN6d+2T+f1VA+Tru1JuITAeojBSjL+ueSKPUSPyO+w64d622iCwp5nACGRoMVxWX16ZUUSlQoftDjj226Zo+Y5Ag35YUT1U3/Ci+6tvlSXvM2+4TiFuuyOJuhQDg6jtZHyL+i8qdnbrfF/K1WU8/A19iybAw14NrY0p9Yx+dUDV+EMW1A4GcXag2N33sW3PtwvN3W092SwWjB+cHKF6RnwC5kljqhhhISsZpGAkXF3zRQOCKwd36bD0FadTrNUInx8QOMkmU27XcxSIHkhCP0X84N6IXmlXNQnjaAdu/H1PQOvJeWppVs/HRBNPi/yKWRLsBZ6Kig8zWrsh61hsdq8Hzgk7wuJSDJgzcp3xdpz0dxMyqEEFRhLKB1vsN3/5I9++6JZ6Y8yNqwODwvpaeDWVZzyA3ktl1t8/UtmEzWGwEU="
    # travis encrypt 'GPG_PASSPHRASE="..."'
    - secure: "hzR/A2nSQZGQ5mr2PVVsk7T3NJN3V7X+8GaR2ZZ9Q60EfGA/qf1XX7TfxGp+YAp3xy2naeXPhNbcym2agGYrvwYK7UyT81V36L+D9BG7jaxJWa74oSbW/SM3z2JK/afu9J2nosmP4UkyaWRdf9AoW4MohRebjOUhqxHR8BdxQ72swrq7/Z1iUeovY0XWcqKHVc9KTPDWBAGAcMwanxvlEUQXDCPksyHI5QuJNdj5cWmJXU11pheiZ1KowQLWOX34DxHFkkt1DnciH8pBBXcZ6T/mPzCwL00f9JVVCZbT0fxfhvccfYk6+XZWC+6Niscck9dLr52NIdb8NpqJg1PMMqCcdYayYGdWuqc15gCgxt4nSyUemrNVBD2uidJmucjW8DqAQYK9zxkc7roHw1WipimicJgVRBpTnZnmFL3BKFBDTNb0K+8mmDjtE1RCugRKOnkFlW0KtWMckkpwbxe6jK2NofjRPU0SM+IyesXXSvMMgZMQFtkbhm9OZ46jWVCmXQcf0draAe/Jj4bJmWEwpb9kncirFaiXwclghpfTSGOcsqaG8dNlHv2oCjnbJ8vALJeP5SucjuxskSBJ/nLT4EAGtVsOK9le6JOheiSwlNrfI5bV0zydMJJoNGKyh1P+VKPAc/+mfVCRi+W8yQMJGmMWLwq2IdKSd8+YYta02vs="
  matrix:
    - FIJI_HADOOP_DISTRIBUTION=cdh
      FIJI_HADOOP_DISTRIBUTION_VERSION=5.3.5

deploy:
  - provider: script
    script: ./devtools/create-assemblies-and-deploy-jars
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      # travis encrypt $API_KEY
      secure: MNeUOKbEuT0JPOrtu345JpkakxKVy7FkVp1aU+mKhJMRriHB7YyUHw7nIx1r+tZtMhtaA4x1YoSYcPnj8W6hBmNzSkeMzZGhUcQAAjd/7k7WimB7Ui+gPaoQmWlE9SPj408HsoHe0Zcz/qp/6dMMYYSCNCuk7aCo6PLwOagzzo3DtbU708iTtywcpN4nQ7gf3EP1tyafzO/vqLI2j0dqPzxemY17Brg63XwMBINGODk09sEOt1a3Tak+c+e/h7SVdsaVfkujEi/7j0B7tYV80OsJ2ESmLLpgjnCSSBcXnSunkEt/XxifJ60zZwnNcLCHqhF8RPb2CRoN/OwNu+U89EuaCTjmlxRGo+X9q6PDkDEZx6e3YmPa3QhXqudbY3BD5O5gXejROwKdr9QRRBz8xazXWe53GJlCC1i/5cWNQxqNGcBFTCCIeNMPkeN7IH0ym+Ar9xpImk6RV2egthLgaPFxPxDE5s4gBF1eNLYANVqFmJKCO+0JkGF8vGIb1yFFIGm7t37ojZj+h8AeXUYTjFc2yDDlmkxq7g+DBlb8vjeduzkpxwfATkhYwmmploFcNo2HobD0gxwN80ECobAJ5ToBU+InYAJGwxR2gXUIt5VLetH/LSZwPUHDJOpnB6ukhmRohk+yv0rCyfxHLdqPMTFh7un1AFnpKDPbuBqpgoE=
    file_glob: true
    file:
      - fiji-express/fiji-express/target/fiji-express-lib-*-release.tar.gz
      - fiji-express/fiji-express-examples/target/fiji-express-examples-*-release.tar.gz
      - fiji-express/fiji-express-tools/target/fiji-express-tools-*-release.tar.gz
      - fiji-express-music/target/fiji-express-music-*-release.tar.gz
      - fiji-hive-adapter/fiji-hive-adapter/target/fiji-hive-lib-*-release.tar.gz
      - fiji-hive-adapter/fiji-hive-tools/target/fiji-hive-tools-*-release.tar.gz
      - fiji-mapreduce/fiji-mapreduce/target/fiji-mapreduce-*-release.tar.gz
      - fiji-mapreduce/fiji-mapreduce-cassandra/target/fiji-mapreduce-cassandra-*-release.tar.gz
      - fiji-modeling/fiji-modeling/target/fiji-modeling-*-release.tar.gz
      - fiji-modeling/fiji-modeling-examples/target/fiji-modeling-examples-*-release.tar.gz
      - fiji-music/target/fiji-music-*-release.tar.gz
      - fiji-phonebook/target/fiji-phonebook-*-release.tar.gz
      - fiji-rest/fiji-rest/target/fiji-rest-lib-*-release.tar.gz
      - fiji-schema/fiji-schema/target/fiji-schema-*-release.tar.gz
      - fiji-schema/fiji-schema-cassandra/target/fiji-schema-cassandra-*-release.tar.gz
      - fiji-schema-shell/target/fiji-schema-shell-lib-*-release.tar.gz
    skip_cleanup: true
    on:
      tags: true
