#! /bin/bash

# Die on error
set -e

date

root=$(pwd)

./bin/fiji-build build # TODO(phs): test

find . -name target -prune -o -name pom.xml -print | \
  xargs grep -l '<groupId>com.moz.fiji' | \
while read f
do
  d=$(dirname $f)

  echo "======================================================================"
  echo "Building: $d"
  echo "======================================================================"

  (
    cd $d
    $root/bin/fiji-maven --settings $root/devtools/settings.xml \
      test-compile javadoc:javadoc \
      | grep -v "with value '\*' does not match a valid id pattern"

    if ! test -f src/main/assembly/release.xml
    then
      echo "No assembly descriptor, skipping"
      continue
    else
      $root/bin/fiji-maven assembly:single -Ddescriptor=src/main/assembly/release.xml \
        | grep -v "with value '\*' does not match a valid id pattern"
    fi
  )
done
