#! /bin/bash

set -e

root=$(pwd)

find . -name target -prune -o -name release.xml -print | while read f
do
  d=$(dirname $f)
  if ! test -f $d/../../../pom.xml
  then
    echo "Skipping: $d"
    continue
  fi

  echo "Assembling: $d"
  (
    cd $d/../../..
    $root/bin/fiji-maven assembly:single -Ddescriptor=src/main/assembly/release.xml \
      | grep -v "with value '\*' does not match a valid id pattern"
  )
done
