#! /bin/bash

# Die on error, even in pipes
set -x -e -o pipefail

# Create jars suitable for uploading Fiji to the Maven central repository at
# https://oss.sonatype.org/

# ASSUMPTIONS:
# 1. You have built Fiji.
# 2. You are running this script from the project root directory.
# 3. You have gpg installed and configured

# http://central.sonatype.org/pages/manual-staging-bundle-creation-and-deployment.html

date

root=$(pwd)
version=$(<FIJI_VERSION)

find "${root}/output/maven_repository" -name '*.pom' | \
grep "/${version}/" | \
xargs grep -l '<groupId>com.moz.fiji' | \
while read f
do
  d=$(dirname $f)
  base=$(basename $f | sed 's|\.pom$||')

  cd $d

  main_jar="${base}.jar"
  sources_jar="${base}-sources.jar"
  javadoc_jar="${base}-javadoc.jar"

  # No artifact? don't try to deploy it
  if ! test -f "${main_jar}"
  then
    continue
  fi

  set +x
  echo "======================================================================"
  echo "Deploying: $d"
  echo "======================================================================"
  set -x

  # Create stub source and javadoc jars if necessary
  if ! test -f "${sources_jar}"
  then
    jar -cf "${sources_jar}" $(basename $f)
  fi

  if ! test -f "${javadoc_jar}"
  then
    jar -cf "${javadoc_jar}" $(basename $f)
  fi

  cp "${main_jar}" /tmp/
  cp "${sources_jar}" /tmp/
  cp "${javadoc_jar}" /tmp/

  $root/bin/fiji-maven gpg:sign-and-deploy-file \
    --settings $root/devtools/settings.xml -DrepositoryId=ossrh -Dpackaging=jar \
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
    -DpomFile=${base}.pom "-Dfile=/tmp/${main_jar}" \
    | grep -v "with value '\*' does not match a valid id pattern"

  $root/bin/fiji-maven gpg:sign-and-deploy-file \
    --settings $root/devtools/settings.xml -DrepositoryId=ossrh -Dpackaging=jar \
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
    -DpomFile=${base}.pom "-Dfile=/tmp/${sources_jar}" -Dclassifier=sources \
    | grep -v "with value '\*' does not match a valid id pattern"

  $root/bin/fiji-maven gpg:sign-and-deploy-file \
    --settings $root/devtools/settings.xml -DrepositoryId=ossrh -Dpackaging=jar \
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
    -DpomFile=${base}.pom "-Dfile=/tmp/${javadoc_jar}" -Dclassifier=javadoc \
    | grep -v "with value '\*' does not match a valid id pattern"
done
