#! /bin/bash

set -e

# Create jars suitable for uploading Fiji to the Maven central repository at
# https://oss.sonatype.org/

# ASSUMPTIONS:
# 1. You have built Fiji.
# 2. You are running this script from the project root directory.
# 3. You have gpg installed and configured

root=$(pwd)

find . -name target -prune -o -name pom.xml -print | \
  xargs grep -l '<groupId>com.moz.fiji' | \
while read f
do
  d=$(dirname $f)
  echo "Deploying: $d"
  (
    cd $d
    $root/bin/fiji-maven deploy --settings $root/devtools/settings.xml \
      -DperformRelease=true -DskipTests=true
  )
done
