#! /bin/bash

# Die on error, even in pipes
set -e -o pipefail

# Create jars suitable for uploading Fiji to the Maven central repository at
# https://oss.sonatype.org/

# ASSUMPTIONS:
# 1. You have built Fiji.
# 2. You are running this script from the project root directory.
# 3. You have gpg installed and configured

# http://central.sonatype.org/pages/manual-staging-bundle-creation-and-deployment.html

cat > /tmp/things-we-care-about <<'EOF'
com/moz/fiji/annotations/annotations/
com/moz/fiji/checkin/fiji-checkin/
com/moz/fiji/common/fiji-common-flags/
com/moz/fiji/commons/fiji-commons-java/
com/moz/fiji/delegation/fiji-delegation/
com/moz/fiji/mapreduce/cdh5-mrbridge/
com/moz/fiji/mapreduce/fiji-mapreduce-avro-lib/
com/moz/fiji/mapreduce/fiji-mapreduce/
com/moz/fiji/mapreduce/platform-api/
com/moz/fiji/schema/cdh5-bridge/
com/moz/fiji/schema/fiji-schema-avro/
com/moz/fiji/schema/fiji-schema-extras/
com/moz/fiji/schema/fiji-schema-shell-lib/
com/moz/fiji/schema/fiji-schema/
com/moz/fiji/schema/schema-platform-api/
EOF

date
gpg --version

root=$(pwd)
version=$(<FIJI_VERSION)

find "${root}/output/maven_repository" -name '*.pom' | \
grep "/${version}/" | \
xargs grep -l '<groupId>com.moz.fiji' | \
grep -f /tmp/things-we-care-about | \
sort | \
while read f
do
  d=$(dirname $f)
  base=$(basename $f | sed 's|\.pom$||')

  cd $d

  main_jar="${base}.jar"
  sources_jar="${base}-sources.jar"
  javadoc_jar="${base}-javadoc.jar"

  # No artifact? don't try to deploy it
  if ! test -f "${main_jar}"
  then
    continue
  fi

  echo "======================================================================"
  echo "Deploying: $d"
  echo "======================================================================"

  main_dir=$(mktemp -d)
  cp "${main_jar}" $main_dir/

  # https://github.com/making/travis-ci-maven-deploy-skelton
  $root/bin/fiji-maven gpg:sign-and-deploy-file \
    --settings $root/devtools/settings.xml \
    -DrepositoryId=ossrh \
    -Dpackaging=jar \
    -DretryFailedDeploymentCount=10 \
    -Dgpg.executable=gpg \
    -Dgpg.ascDirectory="$main_dir" \
    -Dgpg.homedir="$main_dir" \
    -Dgpg.keyname="${GPG_KEYNAME}" \
    -Dgpg.passphrase="${GPG_PASSPHRASE}" \
    -Dgpg.defaultKeyring=false \
    -Dgpg.publicKeyring="${TRAVIS_BUILD_DIR}/devtools/pubring.gpg" \
    -Dgpg.secretKeyring="${TRAVIS_BUILD_DIR}/devtools/secring.gpg" \
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
    -DpomFile=${base}.pom \
    -Dfile="$main_dir/${main_jar}" \
    | grep -v "with value '\*' does not match a valid id pattern" &

  sleep 1

  # Synthesize if necessary
  if ! test -f "${sources_jar}"
  then
    jar -cf "${sources_jar}" $f
  fi

  sources_dir=$(mktemp -d)
  cp "${sources_jar}" $sources_dir/

  $root/bin/fiji-maven gpg:sign-and-deploy-file \
    --settings $root/devtools/settings.xml \
    -DrepositoryId=ossrh \
    -Dpackaging=jar \
    -DretryFailedDeploymentCount=10 \
    -Dgpg.executable=gpg \
    -Dgpg.ascDirectory="$sources_dir" \
    -Dgpg.homedir="$sources_dir" \
    -Dgpg.keyname="${GPG_KEYNAME}" \
    -Dgpg.passphrase="${GPG_PASSPHRASE}" \
    -Dgpg.defaultKeyring=false \
    -Dgpg.publicKeyring="${TRAVIS_BUILD_DIR}/devtools/pubring.gpg" \
    -Dgpg.secretKeyring="${TRAVIS_BUILD_DIR}/devtools/secring.gpg" \
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
    -DpomFile=${base}.pom \
    -Dfile="$sources_dir/${sources_jar}" \
    -Dclassifier=sources \
    | grep -v "with value '\*' does not match a valid id pattern" &

  sleep 1

  # Synthesize if necessary
  if ! test -f "${javadoc_jar}"
  then
    jar -cf "${javadoc_jar}" $f
  fi

  javadoc_dir=$(mktemp -d)
  cp "${javadoc_jar}" $javadoc_dir/

  $root/bin/fiji-maven gpg:sign-and-deploy-file \
    --settings $root/devtools/settings.xml \
    -DrepositoryId=ossrh \
    -Dpackaging=jar \
    -DretryFailedDeploymentCount=10 \
    -Dgpg.executable=gpg \
    -Dgpg.ascDirectory="$javadoc_dir" \
    -Dgpg.homedir="$javadoc_dir" \
    -Dgpg.keyname="${GPG_KEYNAME}" \
    -Dgpg.passphrase="${GPG_PASSPHRASE}" \
    -Dgpg.defaultKeyring=false \
    -Dgpg.publicKeyring="${TRAVIS_BUILD_DIR}/devtools/pubring.gpg" \
    -Dgpg.secretKeyring="${TRAVIS_BUILD_DIR}/devtools/secring.gpg" \
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
    -DpomFile=${base}.pom \
    -Dfile="$javadoc_dir/${javadoc_jar}" \
    -Dclassifier=javadoc \
    | grep -v "with value '\*' does not match a valid id pattern" &

  sleep 1

  while (( $(jobs -p | wc -l) > 6 ))
  do
    wait -n
  done
done

wait

$root/bin/fiji-maven org.sonatype.plugins:nexus-staging-maven-plugin:release \
  --settings $root/devtools/settings.xml \
  -DserverId=ossrh \
  -DnexusUrl=https://oss.sonatype.org/ \
  -DautoReleaseAfterClose=true
